name: post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull_request: write
jobs:
  build:
    name: post welcome comment
    runs_on: ubuntu-latest
  steps:
    - run: gh pr comment $PR_URL --body "Welcome to the repository!"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
    
    
